#!/bin/bash
set -e

# base configuration directory
LOCAL_USER=$(id -un)
DIR="/home/$LOCAL_USER/.config/mem_daemon"
# number of columns for pretty select case
COLUMNS=12

# option menu
options=(
    "Install memory daemon"
    "Edit md.conf"
    "Test memory daemon with dummy trigger"
    "Add crontab for memory daemon"
    "Uninstall memory daemon"
)

# installation function
function install_mem_daemon(){
    echo  "checking for existence of $DIR and /home/$LOCAL_USER/bin; creating where necessary... "
    mkdir -p $DIR
    mkdir -p "/home/$LOCAL_USER/bin"
    echo "copying default md.conf to $DIR..."
    if [ -f $DIR/md.conf ]; then
        read -rep "keep previous md.conf configuration? (y|n): " ans
        if [ "$ans" == "n" ]; then
           mv $DIR/md.conf $DIR/md.conf.bak
           cp ./aux/md.conf $DIR/md.conf
        fi
    else
        cp ./aux/md.conf $DIR/md.conf
    fi
    if [ -z $(echo $PATH | grep "/home/$LOCAL_USER/bin") ]; then
        echo "adding /home/$LOCAL_USER/bin to system path"
        echo "export PATH=$PATH:/home/$LOCAL_USER/bin" >> /home/$LOCAL_USER/.bashrc
        source /home/$LOCAL_USER/.profile
    fi
    echo "copying executables to /home/$LOCAL_USER/bin..."
    cp mem_daemon /home/$LOCAL_USER/bin/mem_daemon
    cp mem_daemon_mail.py /home/$LOCAL_USER/bin/mem_daemon_mail
    chmod +x /home/$LOCAL_USER/bin/mem_daemon_mail
    echo "installation complete! fill out $DIR/md.conf with email-related details to use this service"
}

# uninstallation function
function uninstall_mem_daemon(){
    # remove executables
    echo "removing executables from /home/$LOCAL_USER/bin..."
    rm -f /home/$LOCAL_USER/bin/mem_daemon
    rm -f /home/$LOCAL_USER/bin/mem_daemon_mail
    # remove crontab
    read -rep "remove mem_daemon crontab (if it exists)? (y|n): " ans
    if [ "$ans" == "y" ]; then
        crontab -l > $DIR/mycron
        # echo new cron into cron file
        sed -i "/mem_daemon/d" $DIR/mycron
        # install new cron file
        crontab $DIR/mycron
        rm $DIR/mycron
    fi
}

# case selection plan
select option in "${options[@]}"; do
    case "$REPLY" in
        1) install_mem_daemon
           break
           ;;
        2) vim $DIR/md.conf
	         break
	         ;;
        3) echo "An email will be sent to your specified address but fret not; no process will be killed"
           /home/$LOCAL_USER/bin/mem_daemon 1 1
	         break
	         ;;
        4) # execute dummy check to see if all variables are defined
           /home/$LOCAL_USER/bin/mem_daemon 1 0
           if [ $(echo $?) -eq 2 ]; then
              echo "please fill out $DIR/md.conf before setting up a crontab"
              exit 1
           fi
           # check if crontab is already installed
           if [ -z "$(crontab -l | grep mem_daemon)" ]; then
                # write out current crontab
                read -rep "With what periodicity should memory be checked (in minutes) ?: " ans
                crontab -l > $DIR/mycron
                # echo new cron into cron file
                echo "*/$ans * * * * /home/$LOCAL_USER/bin/mem_daemon 0 1 >> $DIR/tmp.log" >> $DIR/mycron
                # install new cron file
                crontab $DIR/mycron
                rm $DIR/mycron
           else
                echo "crontab already installed"
           fi
           break
           ;;
	      5) uninstall_mem_daemon
	         break
	         ;;
    esac
done
